package Simulator;

public enum PlayerState {
    IN_LOBBY,
    WALKING,
    WAITING_CASHIER,
    EXCHANGING,
    FINDING_TABLE,
    FINDING_SLOT_MACHINE,
    WAITING_GAME_START,
    IN_GAME_SLOT_MACHINE,
    IN_GAME_CROUPIER,
    WAITING_GAME_END,
    LEAVING,
    ENTERING,
    DECIDING,
    IN_GAME_AREA;
}
